'use strict';
function newReceiptId(){if(typeof globalThis.crypto?.randomUUID==='function')return globalThis.crypto.randomUUID();const bytes=new Uint8Array(16);if(typeof globalThis.crypto?.getRandomValues==='function')globalThis.crypto.getRandomValues(bytes);else for(let i=0;i<16;i++)bytes[i]=Math.floor(Math.random()*256);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return hex.slice(0,8)+'-'+hex.slice(8,12)+'-'+hex.slice(12,16)+'-'+hex.slice(16,20)+'-'+hex.slice(20);}
const $=id=>document.getElementById(id), key='bsc-stock-v3';
let draft={branch:'',employee:'',values:{},sizes:{},id:newReceiptId()},category='All products',busy=false;
try{const saved=JSON.parse(localStorage.getItem(key)||localStorage.getItem('bsc-stock-v2'));if(saved&&saved.values&&typeof saved.values==='object'&&typeof saved.id==='string')draft=saved;}catch{}
PRODUCTS.filter(p=>p.sizes.length).forEach(p=>{if(typeof draft.values[p.id]==='string'){const old=draft.values[p.id],size=draft.sizes?.[p.id];draft.values[p.id]=Object.fromEntries(p.sizes.map(s=>[s,s===size?old:'']));}});
const categories=[...new Set(PRODUCTS.map(p=>p.category))];
const el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
const branch=el(CONFIG.branches.length?'select':'input');branch.id='branch';branch.required=true;
if(CONFIG.branches.length){branch.append(new Option('Select your branch',''));CONFIG.branches.forEach(b=>branch.append(new Option(b,b)));}else{branch.placeholder='Enter your branch name';branch.maxLength=100;}
$('branchControl').append(branch);branch.value=new URLSearchParams(location.search).get('branch')||draft.branch||'';$('employee').value=draft.employee||'';
function save(){draft.branch=branch.value;draft.employee=$('employee').value;try{localStorage.setItem(key,JSON.stringify(draft));}catch{$('status').textContent='Draft storage is unavailable. Keep this page open until you submit.';}update();}
function valid(v){return typeof v==='string'&&v.trim()!==''&&Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=1000000000;}
function complete(p){return p.sizes.length?p.sizes.every(s=>valid(draft.values[p.id]?.[s])):valid(draft.values[p.id]);}
function summary(){let filled=0,partial=0,blank=0,fields=0;PRODUCTS.forEach(p=>{const quantities=p.sizes.length?p.sizes.map(s=>draft.values[p.id]?.[s]):[draft.values[p.id]];const n=quantities.filter(valid).length;fields+=n;if(n===quantities.length)filled++;else if(n)partial++;else blank++;});return {filled,partial,blank,fields};}
function update(){const n=PRODUCTS.filter(p=>complete(p)).length;$('count').replaceChildren(document.createTextNode(n+' '),el('small','','/ '+PRODUCTS.length+' counted'));$('bar').style.width=n/PRODUCTS.length*100+'%';$('ready').textContent=n===PRODUCTS.length?'All items counted · Ready for review':(PRODUCTS.length-n)+' products incomplete · You can submit a partial count';}
function renderNav(){const nav=$('categories');nav.replaceChildren();['All products',...categories].forEach(c=>{const b=el('button',category===c?'active':'');b.type='button';b.append(el('span','',c),el('small','',c==='All products'?PRODUCTS.length:PRODUCTS.filter(p=>p.category===c).length));b.onclick=()=>{category=c;renderNav();render();};nav.append(b);});}
function render(){
const q=$('search').value.toLowerCase(),only=$('remaining').checked,root=$('products');root.replaceChildren();let visible=0;
categories.forEach(c=>{const items=PRODUCTS.filter(p=>p.category===c&&(category==='All products'||category===c)&&(p.name+' '+p.code).toLowerCase().includes(q)&&(!only||!complete(p)));if(!items.length)return;visible+=items.length;
const title=el('div','group-title');title.append(el('b','',c),el('span','',items.length+' items'));root.append(title);
items.forEach(p=>{const row=el('div','row'),info=el('div'),label=el('label','',p.name+' ('+p.unit+')');label.htmlFor=p.id;info.append(label,el('small','',p.code+' · '+p.unit));
const qty=el('div','quantity');
const addQuantity=(size)=>{const wrap=el('div','quantity-field'),input=el('input');input.type='number';input.id=size?p.id+'-'+size.replaceAll(' ',''):p.id;input.min='0';input.max='1000000000';input.step='any';input.placeholder='Qty';input.required=false;input.setAttribute('aria-label',p.name+' '+(size?size+' bottle':p.unit)+' quantity');input.value=size?draft.values[p.id]?.[size]??'':draft.values[p.id]??'';input.addEventListener('input',()=>{if(size){draft.values[p.id]=draft.values[p.id]||{};draft.values[p.id][size]=input.value;}else draft.values[p.id]=input.value;input.classList.toggle('invalid',input.value!==''&&!valid(input.value));save();});if(size){const sizeLabel=el('label','',size+' × BTL');sizeLabel.htmlFor=input.id;wrap.append(sizeLabel);}wrap.append(input);if(!size)wrap.append(el('span','',p.unit));qty.append(wrap);};if(p.sizes.length){qty.classList.add('bottle-quantities');p.sizes.forEach(addQuantity);}else addQuantity();row.append(info,qty);root.append(row);});});$('empty').hidden=visible>0;}

branch.oninput=save;$('employee').oninput=save;$('search').oninput=render;$('remaining').onchange=render;
$('stock').onsubmit=e=>{e.preventDefault();if(busy)return;save();branch.classList.toggle('invalid',!branch.value.trim());$('employee').classList.toggle('invalid',!$('employee').value.trim());if(!branch.value.trim()||!$('employee').value.trim()){$('status').textContent='Please enter branch and employee name.';(!branch.value.trim()?branch:$('employee')).focus();return;}const invalid=PRODUCTS.flatMap(p=>p.sizes.length?p.sizes.map(s=>({id:p.id+'-'+s.replaceAll(' ',''),v:draft.values[p.id]?.[s]})):[{id:p.id,v:draft.values[p.id]}]).find(x=>x.v!==undefined&&x.v!==''&&!valid(x.v));if(invalid){category='All products';$('search').value='';$('remaining').checked=false;renderNav();render();$(invalid.id).classList.add('invalid');$(invalid.id).focus();$('status').textContent='Enter a valid non-negative quantity, or leave it blank.';return;}const counts=summary();if(!counts.fields){$('status').textContent='Enter at least one quantity before submitting.';return;}$('reviewDetails').textContent=draft.branch+' · '+draft.employee+' | '+counts.filled+' filled, '+counts.partial+' partly filled, '+counts.blank+' not filled out of '+PRODUCTS.length+' products. Blank quantities will stay blank in the report.';$('review').showModal();};
$('back').onclick=()=>$('review').close();
function receipt(id){return new Promise((resolve,reject)=>{const script=el('script');let timer;window.bscReceipt=result=>{clearTimeout(timer);script.remove();delete window.bscReceipt;resolve(result);};script.src=CONFIG.endpoint+'?action=status&id='+encodeURIComponent(id)+'&callback=bscReceipt&t='+Date.now();script.onerror=()=>{clearTimeout(timer);script.remove();delete window.bscReceipt;reject(new Error('Unable to check receipt'));};timer=setTimeout(()=>{script.remove();delete window.bscReceipt;reject(new Error('Receipt check timed out'));},10000);document.body.append(script);});}
$('confirm').onclick=async()=>{if(busy)return;busy=true;$('confirm').disabled=true;$('submit').disabled=true;$('review').close();$('status').textContent='Sending stock count…';try{const body=new URLSearchParams({payload:JSON.stringify({id:draft.id,branch:draft.branch.trim(),employee:draft.employee.trim(),values:draft.values,sizes:draft.sizes||{}})});await fetch(CONFIG.endpoint,{method:'POST',mode:'no-cors',body});let result;for(let i=0;i<8;i++){await new Promise(r=>setTimeout(r,1500));result=await receipt(draft.id);if(result.saved)break;}if(!result?.saved)throw new Error('Save could not be confirmed');$('status').textContent='Saved to Google Sheets. Email: '+(result.emailStatus==='Sent'?'sent to Samad with Faizal CC':'queued / '+(result.emailStatus||'pending'))+'. Receipt: '+draft.id;try{localStorage.removeItem(key);}catch{}draft.id=newReceiptId();}catch{$('status').textContent='Save was not confirmed. Your draft is retained; check the Sheet or retry. A retry uses the same receipt ID to prevent duplicates.';}finally{busy=false;$('confirm').disabled=false;$('submit').disabled=!CONFIG.endpoint;}};
$('setup').hidden=!!CONFIG.endpoint;$('submit').disabled=!CONFIG.endpoint;renderNav();render();save();
