'use strict';
function loadCatalogue(){const box=document.getElementById('catalogLoading');box.hidden=false;document.getElementById('stock').hidden=true;return new Promise((resolve,reject)=>{const script=document.createElement('script');let timer;function cleanup(){clearTimeout(timer);script.remove();delete window.bscSecurity;}window.bscSecurity=info=>{cleanup();box.hidden=true;resolve(info);};script.src=CONFIG.endpoint+'?action=securityInfo&t='+Date.now();script.onerror=()=>{cleanup();reject(Error('Unable to load the product list. Check your internet connection and reload.'));};timer=setTimeout(()=>{cleanup();reject(Error('The product list is taking longer to load. Please reload and try again. Your saved draft is retained.'));},45000);document.body.append(script);});}
(async function startInventory(){
const securityInfo=await loadCatalogue();
if(securityInfo.catalogVersion===FINAL_CATALOG_VERSION){if(!securityInfo.costsReady)throw Error('The updated inventory list is being prepared. Please contact the administrator and try again shortly.');PRODUCTS=FINAL_PRODUCTS;}
const activeCatalogVersion=PRODUCTS===FINAL_PRODUCTS?FINAL_CATALOG_VERSION:'legacy-v4';
CONFIG.branchSecurity=!!securityInfo.enabled;CONFIG.maxByUnit=securityInfo.maxByUnit||{};CONFIG.wholeUnits=securityInfo.wholeUnits||[];CONFIG.pinRequired=securityInfo.pinRequired!==false;

function newReceiptId(){if(typeof globalThis.crypto?.randomUUID==='function')return globalThis.crypto.randomUUID();const bytes=new Uint8Array(16);if(typeof globalThis.crypto?.getRandomValues==='function')globalThis.crypto.getRandomValues(bytes);else for(let i=0;i<16;i++)bytes[i]=Math.floor(Math.random()*256);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return hex.slice(0,8)+'-'+hex.slice(8,12)+'-'+hex.slice(12,16)+'-'+hex.slice(16,20)+'-'+hex.slice(20);}
const $=id=>document.getElementById(id), key='bsc-stock-v3';
let draft={branch:'',employee:'',values:{},sizes:{},id:newReceiptId()},category='All products',busy=false;
try{const saved=JSON.parse(localStorage.getItem(key)||localStorage.getItem('bsc-stock-v2'));if(saved&&saved.values&&typeof saved.values==='object'&&typeof saved.id==='string')draft=saved;}catch{}
let migrationNotice='';
if(activeCatalogVersion===FINAL_CATALOG_VERSION&&!draft.submitted&&draft.catalogVersion!==FINAL_CATALOG_VERSION){const savedValues=draft.values||{},previous=Object.fromEntries(LEGACY_PRODUCTS.map(p=>[p.id,p])),migrated={};let reviewCount=0;try{if(Object.keys(savedValues).length)localStorage.setItem('bsc-draft-before-'+FINAL_CATALOG_VERSION,JSON.stringify(draft));}catch{}for(const p of PRODUCTS){const before=previous[p.id];if(!before||before.unit!==p.unit){if(savedValues[p.id]!==undefined)reviewCount++;continue;}if(p.sizes.length){if(typeof savedValues[p.id]==='object'&&savedValues[p.id]!==null){migrated[p.id]={};p.sizes.forEach(size=>{if(before.sizes.includes(size)&&typeof savedValues[p.id][size]==='string')migrated[p.id][size]=savedValues[p.id][size];});if(p.sizes.some(size=>!before.sizes.includes(size)))reviewCount++;}}else if(!before.sizes.length&&typeof savedValues[p.id]==='string')migrated[p.id]=savedValues[p.id];else if(savedValues[p.id]!==undefined)reviewCount++;}draft.values=migrated;draft.sizes={};draft.page=0;draft.category='All products';if(Object.keys(savedValues).length)migrationNotice='The product list has been updated to the final Branches list. Counts with matching units were retained.'+(reviewCount?' Please recount '+reviewCount+' products whose units or sizes changed.':'')+' All remaining quantities must be checked before submitting.';}
$('catalogueCount').textContent=PRODUCTS.length;
$('catalogNotice').textContent=migrationNotice;$('catalogNotice').hidden=!migrationNotice;
$('stock').hidden=false;$('submit').disabled=true;
PRODUCTS.filter(p=>p.sizes.length).forEach(p=>{if(typeof draft.values[p.id]==='string'){const old=draft.values[p.id],size=draft.sizes?.[p.id];draft.values[p.id]=Object.fromEntries(p.sizes.map(s=>[s,s===size?old:'']));}});
const pageSize=20;let page=Number.isInteger(draft.page)?Math.max(0,draft.page):0;
const categories=[...new Set(PRODUCTS.map(p=>p.category))];
const el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
const branch=el(CONFIG.branches.length?'select':'input');branch.id='branch';branch.required=true;
if(CONFIG.branches.length){branch.append(new Option('Select your branch',''));CONFIG.branches.filter(b=>b!=='IT- Testing'||securityInfo.testBranch==='IT- Testing').forEach(b=>branch.append(new Option(b,b)));}else{branch.placeholder='Enter your branch name';branch.maxLength=100;}
$('branchControl').append(branch);branch.value=new URLSearchParams(location.search).get('branch')||draft.branch||'';$('employee').value=draft.employee||'';
function save(){draft.catalogVersion=activeCatalogVersion;draft.page=page;draft.category=category;draft.branch=branch.value;draft.employee=$('employee').value;try{localStorage.setItem(key,JSON.stringify(draft));}catch{$('status').textContent='Draft storage is unavailable. Keep this page open until you submit.';}update();}
function isTesting(){return branch.value==='IT- Testing'&&securityInfo.testBranch==='IT- Testing';}
function valid(v){return typeof v==='string'&&v.trim()!==''&&Number.isFinite(Number(v))&&Number(v)>=0;}
function complete(p){return p.sizes.length?p.sizes.every(s=>valid(draft.values[p.id]?.[s])):valid(draft.values[p.id]);}
function summary(){let filled=0,partial=0,blank=0,fields=0;PRODUCTS.forEach(p=>{const quantities=p.sizes.length?p.sizes.map(s=>draft.values[p.id]?.[s]):[draft.values[p.id]];const n=quantities.filter(valid).length;fields+=n;if(n===quantities.length)filled++;else if(n)partial++;else blank++;});return {filled,partial,blank,fields};}
function update(){const n=PRODUCTS.filter(p=>complete(p)).length;$('count').replaceChildren(document.createTextNode(n+' '),el('small','','/ '+PRODUCTS.length+' counted'));$('bar').style.width=n/PRODUCTS.length*100+'%';$('quantityInstructions').textContent=isTesting()?'IT testing only: product quantities are optional. Fill any items you want to test; blank fields remain uncounted.':'Enter quantities in the listed units. Where bottle sizes are listed, enter each size separately. All product quantities are mandatory. Enter 0 for no stock.';$('ready').textContent=isTesting()?'IT testing · Product quantities optional · Ready for review':n===PRODUCTS.length?'All items counted · Ready for review':(PRODUCTS.length-n)+' products left · All quantities are required';}
function renderNav(){const nav=$('categories');nav.replaceChildren();['All products',...categories].forEach(c=>{const b=el('button',category===c?'active':'');b.type='button';b.append(el('span','',c),el('small','',c==='All products'?PRODUCTS.length:PRODUCTS.filter(p=>p.category===c).length));b.onclick=()=>{category=c;page=0;renderNav();render();save();};nav.append(b);});}
function render(){
const q=$('search').value.toLowerCase(),only=$('remaining').checked,root=$('products');root.replaceChildren();let visible=0;
const filtered=categories.flatMap(c=>PRODUCTS.filter(p=>p.category===c&&(category==='All products'||category===c)&&(p.name+' '+p.code).toLowerCase().includes(q)&&(!only||!complete(p))));
const pages=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,pages-1);const shown=filtered.slice(page*pageSize,(page+1)*pageSize);
$('pageInfo').textContent='Page '+(page+1)+' of '+pages+' · '+filtered.length+' products';$('previousPage').disabled=page===0;$('nextPage').disabled=page>=pages-1;

categories.forEach(c=>{const items=shown.filter(p=>p.category===c);if(!items.length)return;visible+=items.length;
const title=el('div','group-title');title.append(el('b','',c),el('span','',items.length+' items'));root.append(title);
items.forEach(p=>{const row=el('div','row'),info=el('div'),label=el('label','',(p.sequence||PRODUCTS.indexOf(p)+1)+'. '+p.name+' ('+p.unit+')');label.htmlFor=p.id;info.append(label,el('small','',p.code+' · '+p.unit));
const qty=el('div','quantity');
const addQuantity=(size)=>{const wrap=el('div','quantity-field'),input=el('input');input.type='number';input.id=size?p.id+'-'+size.replaceAll(' ',''):p.id;input.min='0';input.step='any';input.placeholder='Qty';input.required=!isTesting();input.setAttribute('aria-label',p.name+' '+(size?size+' bottle':p.unit)+' quantity');input.value=size?draft.values[p.id]?.[size]??'':draft.values[p.id]??'';input.addEventListener('input',()=>{if(size){draft.values[p.id]=draft.values[p.id]||{};draft.values[p.id][size]=input.value;}else draft.values[p.id]=input.value;input.classList.toggle('invalid',input.value!==''&&!valid(input.value));save();});if(size){const sizeLabel=el('label','',size+' × BTL');sizeLabel.htmlFor=input.id;wrap.append(sizeLabel);}wrap.append(input);if(!size)wrap.append(el('span','',p.unit));qty.append(wrap);};if(p.sizes.length){qty.classList.add('bottle-quantities');p.sizes.forEach(addQuantity);}else addQuantity();row.append(info,qty);root.append(row);});});$('empty').hidden=visible>0;}

branch.oninput=()=>{render();save();};$('employee').oninput=save;$('search').oninput=()=>{page=0;render();save();};$('remaining').onchange=()=>{page=0;render();save();};
function changePage(delta){page+=delta;render();save();$('inventoryStart').scrollIntoView({behavior:'smooth',block:'start'});}
$('previousPage').onclick=()=>changePage(-1);$('nextPage').onclick=()=>changePage(1);
$('stock').onsubmit=e=>{e.preventDefault();if(busy||restoreSubmitted())return;save();if(CONFIG.pinRequired&&!/^\d{6}$/.test($('branchPin').value)){$('status').textContent='Enter your branch 6-digit PIN.';$('branchPin').focus();return;}branch.classList.toggle('invalid',!branch.value.trim());$('employee').classList.toggle('invalid',!$('employee').value.trim());if(!branch.value.trim()||!$('employee').value.trim()){$('status').textContent='Please enter branch and employee name.';(!branch.value.trim()?branch:$('employee')).focus();return;}const invalid=PRODUCTS.flatMap(p=>p.sizes.length?p.sizes.map(s=>({id:p.id+'-'+s.replaceAll(' ',''),v:draft.values[p.id]?.[s]})):[{id:p.id,v:draft.values[p.id]}]).find(x=>x.v!==undefined&&x.v!==''&&!valid(x.v));if(invalid){category='All products';$('search').value='';$('remaining').checked=false;page=Math.floor(categories.flatMap(c=>PRODUCTS.filter(p=>p.category===c)).findIndex(p=>invalid.id===p.id||invalid.id.startsWith(p.id+'-'))/pageSize);renderNav();render();$(invalid.id).classList.add('invalid');$(invalid.id).focus();$('status').textContent='Enter a valid non-negative quantity, or leave it blank.';return;}if(CONFIG.branchSecurity){const issue=quantityIssue();if(issue){$('status').textContent=issue;return;}}const counts=summary();if(!isTesting()&&counts.filled!==PRODUCTS.length){category='All products';$('search').value='';$('remaining').checked=false;const ordered=categories.flatMap(c=>PRODUCTS.filter(p=>p.category===c)),missing=ordered.find(p=>!complete(p));page=Math.floor(ordered.indexOf(missing)/pageSize);renderNav();render();save();const size=missing.sizes.find(s=>!valid(draft.values[missing.id]?.[s]));const target=$(size?missing.id+'-'+size.replaceAll(' ',''):missing.id);target.classList.add('invalid');target.focus();$('status').textContent='All product quantities are mandatory. Enter 0 for no stock. '+(PRODUCTS.length-counts.filled)+' products remain incomplete.';return;}$('reviewDetails').textContent=draft.branch+' · '+draft.employee+' | '+counts.filled+' filled, '+counts.partial+' partly filled, '+counts.blank+' not filled out of '+PRODUCTS.length+' products. '+(isTesting()?'TEST SUBMISSION: quantities are optional; blank fields are uncounted.':'All product quantities have been completed.');$('review').showModal();};
$('back').onclick=()=>$('review').close();
function receipt(id,attempt){return new Promise((resolve,reject)=>{const script=el('script');let timer;window.bscReceipt=result=>{clearTimeout(timer);script.remove();delete window.bscReceipt;resolve(result);};script.src=CONFIG.endpoint+'?action=status&id='+encodeURIComponent(id)+'&attempt='+encodeURIComponent(attempt||'')+'&callback=bscReceipt&t='+Date.now();script.onerror=()=>{clearTimeout(timer);script.remove();delete window.bscReceipt;reject(new Error('Unable to check receipt'));};timer=setTimeout(()=>{script.remove();delete window.bscReceipt;reject(new Error('Receipt check timed out'));},45000);document.body.append(script);});}
$('confirm').onclick=async()=>{if(busy||restoreSubmitted())return;busy=true;$('confirm').disabled=true;$('submit').disabled=true;$('review').close();$('status').textContent='Sending stock count… Reference: '+draft.id;try{const attempt=newReceiptId();const body=new URLSearchParams({payload:JSON.stringify({id:draft.id,catalogVersion:activeCatalogVersion,branch:draft.branch.trim(),employee:draft.employee.trim(),values:draft.values,sizes:draft.sizes||{},pin:$('branchPin').value,website:$('website').value,attempt:attempt})});const controller=new AbortController(),postTimer=setTimeout(()=>controller.abort(),15000);try{await fetch(CONFIG.endpoint,{method:'POST',mode:'no-cors',body,signal:controller.signal});}catch{}finally{clearTimeout(postTimer);}let result;for(let i=0;i<3;i++){$('status').textContent='Checking submission ('+(i+1)+'/3)… Reference: '+draft.id;await new Promise(r=>setTimeout(r,1500));try{result=await receipt(draft.id,attempt);}catch{continue;}if(result.error)throw new Error(result.error);if(result.saved)break;}if(!result?.saved)throw new Error('Save could not be confirmed');$('status').textContent='Saved to Google Sheets. Email: '+(result.emailStatus==='Sent'?'accepted for sending to management':'queued / '+(result.emailStatus||'pending'))+'. Receipt: '+draft.id;const savedReceipt={id:draft.id,branch:draft.branch,employee:draft.employee,emailStatus:result.emailStatus,submittedAt:Date.now()};draft.submitted=true;draft.receipt=savedReceipt;save();try{localStorage.setItem('bsc-last-receipt',JSON.stringify(savedReceipt));}catch{}lockSubmission(true);}catch(err){$('status').textContent=err.message&&err.message!=='Save could not be confirmed'?err.message+' Your draft is retained.':'Submission could not be confirmed. Reference: '+draft.id+'. Your draft is retained. Check with the administrator before retrying; a retry uses this same reference to prevent duplicates.';}finally{busy=false;$('confirm').disabled=!!draft.submitted;$('submit').disabled=!!draft.submitted||!CONFIG.endpoint;}};
category=categories.includes(draft.category)?draft.category:'All products';
$('setup').hidden=!!CONFIG.endpoint;$('submit').disabled=!CONFIG.endpoint;renderNav();render();save();

const countNotice=$('countNotice');
$('acknowledgeCount').onclick=()=>countNotice.close();
const noticeButtons={en:'Understood, continue',hi:'समझ गया, आगे बढ़ें',bn:'বুঝেছি, এগিয়ে যাই'};
function setNoticeLanguage(language){if(!Object.hasOwn(noticeButtons,language))language='en';$('noticeLanguage').value=language;['en','hi','bn'].forEach(code=>{$('notice-'+code).hidden=code!==language;});$('acknowledgeCount').textContent=noticeButtons[language];$('acknowledgeCount').setAttribute('lang',language);}
$('noticeLanguage').onchange=()=>{setNoticeLanguage($('noticeLanguage').value);try{localStorage.setItem('bsc-notice-language',$('noticeLanguage').value);}catch{}};
try{setNoticeLanguage(localStorage.getItem('bsc-notice-language')||'en');}catch{setNoticeLanguage('en');}

// Show the count notice only when this browser is ready for a new count.

function showSubmissionReceipt(receipt,scroll=false){$('submissionReceipt').hidden=false;$('receiptNumber').textContent=receipt.id;$('receiptBranch').textContent='Branch Name: '+receipt.branch;$('receiptEmployee').textContent='Employee Name: '+(receipt.employee||'Not recorded');$('receiptEmail').textContent=receipt.emailStatus==='Sent'?'Inventory report email sent.':'Inventory saved. Report email status: '+(receipt.emailStatus||'Pending')+'.';if(scroll)$('submissionReceipt').scrollIntoView({behavior:'smooth',block:'center'});}
const inventoryCooldown=24*60*60*1000;let cooldownTimer;
function deviceReceipt(){let latest=draft.submitted?draft.receipt:null;try{const stored=JSON.parse(localStorage.getItem('bsc-last-receipt'));if(stored&&typeof stored.id==='string'&&stored.branch&&!Number.isFinite(stored.submittedAt)){stored.submittedAt=Date.now();localStorage.setItem('bsc-last-receipt',JSON.stringify(stored));}if(stored&&Number.isFinite(stored.submittedAt)&&(!latest||!Number.isFinite(latest.submittedAt)||stored.submittedAt>latest.submittedAt))latest=stored;}catch{}if(latest&&!Number.isFinite(latest.submittedAt)&&draft.submitted){latest={...latest,submittedAt:Date.now()};draft.receipt=latest;save();try{localStorage.setItem('bsc-last-receipt',JSON.stringify(latest));}catch{}}return latest;}
function cooldownRemaining(receipt){return receipt&&Number.isFinite(receipt.submittedAt)?Math.max(0,receipt.submittedAt+inventoryCooldown-Date.now()):0;}
function lockSubmission(scroll=false){const saved=draft.receipt||{id:draft.id,branch:draft.branch,employee:draft.employee};const remaining=cooldownRemaining(saved);document.body.classList.add('inventory-submitted');$('stock').hidden=true;$('submit').disabled=true;$('confirm').disabled=true;$('newInventory').hidden=remaining>0;$('submittedNotice').hidden=false;$('submissionTitle').textContent='Inventory already submitted';$('submittedNotice').textContent=remaining>0?'This device can submit a new inventory after '+new Date(saved.submittedAt+inventoryCooldown).toLocaleString('en-GB',{timeZone:'Asia/Riyadh'})+' (Riyadh time).':'The 24-hour waiting period is complete. You can now start a new inventory.';showSubmissionReceipt(saved,scroll);clearTimeout(cooldownTimer);if(remaining>0)cooldownTimer=setTimeout(()=>lockSubmission(),remaining);}
function restoreSubmitted(){const last=deviceReceipt();if(cooldownRemaining(last)>0){draft.submitted=true;draft.receipt=last;lockSubmission();return true;}if(draft.submitted){lockSubmission();return true;}return false;}
$('newInventory').onclick=()=>{if(busy)return;const last=deviceReceipt();if(cooldownRemaining(last)>0){restoreSubmitted();return;}clearTimeout(cooldownTimer);document.body.classList.remove('inventory-submitted');draft={branch:draft.branch,employee:draft.employee,values:{},sizes:{},id:newReceiptId()};page=0;category='All products';$('branchPin').value='';$('search').value='';$('remaining').checked=false;$('stock').hidden=false;$('submissionReceipt').hidden=true;$('newInventory').hidden=true;$('submittedNotice').hidden=true;$('submit').disabled=!CONFIG.endpoint;$('confirm').disabled=false;branch.value=draft.branch;$('employee').value=draft.employee;$('status').textContent='New inventory started. Count all products before submitting.';renderNav();render();save();$('stock').scrollIntoView({behavior:'smooth',block:'start'});};
window.addEventListener('storage',event=>{if(event.key===key||event.key==='bsc-last-receipt')restoreSubmitted();});
window.addEventListener('focus',()=>restoreSubmitted());
document.addEventListener('visibilitychange',()=>{if(!document.hidden)restoreSubmitted();});
function showLockedPopup(){const saved=draft.receipt;if(saved&&cooldownRemaining(saved)>0){$('alreadyReference').textContent=saved.id;$('alreadyBranch').textContent=saved.branch;$('alreadyEmployee').textContent=saved.employee||'Not recorded';$('alreadyRelease').textContent=new Date(saved.submittedAt+inventoryCooldown).toLocaleString('en-GB',{timeZone:'Asia/Riyadh'})+' (Riyadh time)';if(countNotice.open)countNotice.close();if(!$('alreadySubmitted').open)$('alreadySubmitted').showModal();}}
if(restoreSubmitted()){showLockedPopup();}else{countNotice.showModal();try{const last=JSON.parse(localStorage.getItem('bsc-last-receipt'));if(last&&typeof last.id==='string')showSubmissionReceipt(last);}catch{}}

$('closeAlreadySubmitted').onclick=()=>$('alreadySubmitted').close();

function quantityIssue(){for(const p of PRODUCTS){const unit=p.unit.toUpperCase(),head=unit.split('*')[0].trim(),base=/\bBTL\b/.test(unit)?'BTL':/\bBDL\b/.test(unit)?'BDL':head==='UNITS'?'UNIT':head;for(const size of (p.sizes.length?p.sizes:[''])){const value=size?draft.values[p.id]?.[size]:draft.values[p.id];if(!valid(value))continue;const n=Number(value),max=CONFIG.maxByUnit[base];if(Number.isFinite(max)&&n>max)return p.name+': quantity exceeds '+max+'. Please check the count or contact the administrator.';if(CONFIG.wholeUnits.includes(base)&&!Number.isInteger(n))return p.name+': enter a whole-number quantity.';}}return '';}
$('branchPinField').hidden=!CONFIG.pinRequired;

/* Recover a confirmed receipt without posting another inventory. */
async function recoverConfirmedReceipt(){
const recovery=new URLSearchParams((location.hash||'').slice(1)),linkedId=recovery.get('receipt'),id=linkedId||draft.id;
if(draft.submitted||!CONFIG.endpoint||!/^[a-f0-9-]{36}$/.test(id)||(!linkedId&&!Object.keys(draft.values).length))return;
busy=true;$('submit').disabled=true;$('status').textContent='Checking whether this inventory has already been saved…';
try{const result=await receipt(id,'');if(result.saved){const suppliedAt=Date.parse(recovery.get('at')||''),submittedAt=Number.isFinite(suppliedAt)&&suppliedAt<=Date.now()?suppliedAt:Date.now();const saved={id,branch:recovery.get('branch')||draft.branch,employee:recovery.get('employee')||draft.employee,emailStatus:result.emailStatus,submittedAt};draft.id=id;draft.submitted=true;draft.receipt=saved;save();try{localStorage.setItem('bsc-last-receipt',JSON.stringify(saved));}catch{}lockSubmission(true);showLockedPopup();if(linkedId&&window.history?.replaceState)window.history.replaceState(null,'',location.pathname+location.search);}else{$('status').textContent='Your draft is saved on this device. Submission has not been confirmed.';}}catch{$('status').textContent='Unable to check the previous submission. Your draft is retained. Check the reference in your report before submitting again.';}finally{busy=false;$('submit').disabled=!!draft.submitted||!CONFIG.endpoint;}}
recoverConfirmedReceipt();


})().catch(error=>{document.getElementById('stock').hidden=true;document.getElementById('catalogLoading').hidden=false;document.getElementById('catalogLoadingText').textContent=error.message||'Unable to load the product list. Reload and try again.';});
