'use strict';
const $=id=>document.getElementById(id), key='bsc-stock-v2';
let draft={branch:'',employee:'',values:{},sizes:{},id:crypto.randomUUID()},category='All products',busy=false;
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.values&&typeof saved.values==='object'&&typeof saved.id==='string')draft=saved;}catch{}
const categories=[...new Set(PRODUCTS.map(p=>p.category))];
const el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
const branch=el(CONFIG.branches.length?'select':'input');branch.id='branch';branch.required=true;
if(CONFIG.branches.length){branch.append(new Option('Select your branch',''));CONFIG.branches.forEach(b=>branch.append(new Option(b,b)));}else{branch.placeholder='Enter your branch name';branch.maxLength=100;}
$('branchControl').append(branch);branch.value=new URLSearchParams(location.search).get('branch')||draft.branch||'';$('employee').value=draft.employee||'';
function save(){draft.branch=branch.value;draft.employee=$('employee').value;try{localStorage.setItem(key,JSON.stringify(draft));}catch{$('status').textContent='Draft storage is unavailable. Download your count before leaving.';}update();}
function valid(v){return typeof v==='string'&&v.trim()!==''&&Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=1000000000;}
function complete(p){return valid(draft.values[p.id])&&(!p.sizes.length||p.sizes.includes(draft.sizes?.[p.id]));}
function update(){const n=PRODUCTS.filter(p=>complete(p)).length;$('count').replaceChildren(document.createTextNode(n+' '),el('small','','/ PRODUCTS.length counted'));$('bar').style.width=n/PRODUCTS.length*100+'%';$('ready').textContent=n===PRODUCTS.length?'All items counted · Ready for review':(PRODUCTS.length-n)+' items left to count';}
function renderNav(){const nav=$('categories');nav.replaceChildren();['All products',...categories].forEach(c=>{const b=el('button',category===c?'active':'');b.type='button';b.append(el('span','',c),el('small','',c==='All products'?PRODUCTS.length:PRODUCTS.filter(p=>p.category===c).length));b.onclick=()=>{category=c;renderNav();render();};nav.append(b);});}
function render(){
const q=$('search').value.toLowerCase(),only=$('remaining').checked,root=$('products');root.replaceChildren();let visible=0;
categories.forEach(c=>{const items=PRODUCTS.filter(p=>p.category===c&&(category==='All products'||category===c)&&(p.name+' '+p.code).toLowerCase().includes(q)&&(!only||!complete(p)));if(!items.length)return;visible+=items.length;
const title=el('div','group-title');title.append(el('b','',c),el('span','',items.length+' items'));root.append(title);
items.forEach(p=>{const row=el('div','row'),info=el('div'),label=el('label','',p.name+' ('+p.unit+')');label.htmlFor=p.id;info.append(label,el('small','',p.code+' · '+p.unit));
const qty=el('div','quantity');
if(p.sizes.length){const select=el('select','bottle-size');select.id=p.id+'-size';select.required=true;select.setAttribute('aria-label',p.name+' bottle size');select.append(new Option('Choose size',''));p.sizes.forEach(s=>select.append(new Option(s+' × BTL',s)));select.value=draft.sizes?.[p.id]||'';select.onchange=()=>{draft.sizes=draft.sizes||{};draft.sizes[p.id]=select.value;save();};qty.append(select);}
const input=el('input');input.type='number';input.id=p.id;input.min='0';input.max='1000000000';input.step='any';input.placeholder='Qty';input.required=true;input.setAttribute('aria-label',p.name+' quantity in '+p.unit);input.value=draft.values[p.id]??'';input.addEventListener('input',()=>{draft.values[p.id]=input.value;input.classList.toggle('invalid',!valid(input.value));save();});qty.append(input,el('span','',p.unit));row.append(info,qty);root.append(row);});});$('empty').hidden=visible>0;}

branch.oninput=save;$('employee').oninput=save;$('search').oninput=render;$('remaining').onchange=render;
$('download').onclick=()=>{save();const csv=['Code,Product,Unit,Bottle size,Quantity',...PRODUCTS.map(p=>[p.code,p.name,p.unit,draft.sizes?.[p.id]||'',draft.values[p.id]??''].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\r\n');const blob=new Blob(['\ufeffBranch,"'+draft.branch.replaceAll('"','""')+'"\r\nEmployee,"'+draft.employee.replaceAll('"','""')+'"\r\n'+csv],{type:'text/csv;charset=utf-8'});const a=el('a');a.href=URL.createObjectURL(blob);a.download='BlueSky-stock-count.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('stock').onsubmit=e=>{e.preventDefault();if(busy)return;save();branch.classList.toggle('invalid',!branch.value.trim());$('employee').classList.toggle('invalid',!$('employee').value.trim());if(!branch.value.trim()||!$('employee').value.trim()){$('status').textContent='Please enter branch and employee name.';(!branch.value.trim()?branch:$('employee')).focus();return;}const missing=PRODUCTS.find(p=>!valid(draft.values[p.id]));if(missing){category='All products';$('search').value='';$('remaining').checked=false;renderNav();render();$(missing.id).classList.add('invalid');$(missing.id).focus();$('status').textContent='Complete every quantity. Enter 0 when there is no stock.';return;}$('reviewDetails').textContent=draft.branch+' · '+draft.employee;$('review').showModal();};
$('back').onclick=()=>$('review').close();
function receipt(id){return new Promise((resolve,reject)=>{const script=el('script');let timer;window.bscReceipt=result=>{clearTimeout(timer);script.remove();delete window.bscReceipt;resolve(result);};script.src=CONFIG.endpoint+'?action=status&id='+encodeURIComponent(id)+'&callback=bscReceipt&t='+Date.now();script.onerror=()=>{clearTimeout(timer);script.remove();delete window.bscReceipt;reject(new Error('Unable to check receipt'));};timer=setTimeout(()=>{script.remove();delete window.bscReceipt;reject(new Error('Receipt check timed out'));},10000);document.body.append(script);});}
$('confirm').onclick=async()=>{if(busy)return;busy=true;$('confirm').disabled=true;$('submit').disabled=true;$('review').close();$('status').textContent='Sending stock count…';try{const body=new URLSearchParams({payload:JSON.stringify({id:draft.id,branch:draft.branch.trim(),employee:draft.employee.trim(),values:draft.values,sizes:draft.sizes||{}})});await fetch(CONFIG.endpoint,{method:'POST',mode:'no-cors',body});let result;for(let i=0;i<8;i++){await new Promise(r=>setTimeout(r,1500));result=await receipt(draft.id);if(result.saved)break;}if(!result?.saved)throw new Error('Save could not be confirmed');$('status').textContent='Saved to Google Sheets. Receipt: '+draft.id;try{localStorage.removeItem(key);}catch{}draft.id=crypto.randomUUID();}catch{$('status').textContent='Save was not confirmed. Your draft is retained; check the Sheet or retry. A retry uses the same receipt ID to prevent duplicates.';}finally{busy=false;$('confirm').disabled=false;$('submit').disabled=!CONFIG.endpoint;}};
$('setup').hidden=!!CONFIG.endpoint;$('submit').disabled=!CONFIG.endpoint;renderNav();render();save();
