const CONFIG = {
  endpoint: 'https://script.google.com/macros/s/AKfycbwh7_MhfFd-Jx4VwmB968n_M8_bhF8gfRd7dLgI0CD4Djg1MqPmOrYmuQObFm6H-x39/exec',
  branches: [
  "AIRPORT ROAD",
  "FAISALIYAH",
  "KHODARIYAH",
  "SAFWA SAHIK",
  "SAIHAT",
  "FAKHRIYAH",
  "SAHAB 1",
  "SAHAB 2",
  "SAPTCO",
  "ABUHAIDERIYAH",
  "AQRABIYAH",
  "AZIZIYAH 1",
  "DOHA",
  "ESKAN",
  "HALF MOON",
  "JAMA'A",
  "NAFOURA",
  "JESSER 2",
  "RAKAH",
  "TAHLIYAH ABBASI",
  "TAWUN KHALEEJ",
  "JB KURBI",
  "JB TAABA",
  "HASSA 1",
  "HASSA 5",
  "HASSA 6",
  "QATIF",
  "WATANI HOSPITAL",
  "RIYADH 2",
  "RIYADH 4",
  "RIYADH 5",
  "RIYADH 6",
  "RIYADH 8",
  "RIYADH 9",
  "RIYADH 10",
  "HAFAR 1",
  "HAFER 4",
  "NAIRIYAH",
  "IT- Testing"
]
};

