// Paste Catalog.gs beside this file. Run setupInventory once, then deploy as Web app.
const INVENTORY_SHEET_ID='1udtvE2eZvgVbsQgUzz7iM0QlfO_s06j49ePmfZuFkYg';
const INVENTORY_TAB='Inventory Reports v4';
const EMAIL_FROM='inventory@blueskycoffe.com';
function verifyInventorySender(){if(!GmailApp.getAliases().some(a=>a.toLowerCase()===EMAIL_FROM.toLowerCase()))throw Error('Verify inventory@blueskycoffe.com in the deploying Gmail account Send mail as settings first.');console.log('Inventory sender alias verified.');}
const EMAIL_TO='Samad@blueskycoffe.com', EMAIL_CC='Faizal@itdelhi.in';
function spreadsheet_(){return SpreadsheetApp.openById(INVENTORY_SHEET_ID);}
function fields_(){return PRODUCTS.flatMap(p=>p.sizes.length?p.sizes.map(size=>({p:p,size:size})):[{p:p,size:''}]);}
function sheet_(){const ss=spreadsheet_();let sheet=ss.getSheetByName(INVENTORY_TAB);if(!sheet){sheet=ss.insertSheet(INVENTORY_TAB);const headers=['Receipt ID','Submitted at (Riyadh)','Branch Name','Employee Name','Filled products','Partly filled products','Not filled products','Filled quantity fields','Blank quantity fields','Email status','Email error',...fields_().map(f=>f.p.code+' | '+f.p.name+' | '+(f.size?f.size+' BTL':f.p.unit))];if(sheet.getMaxColumns()<headers.length)sheet.insertColumnsAfter(sheet.getMaxColumns(),headers.length-sheet.getMaxColumns());sheet.appendRow(headers);sheet.setFrozenRows(1);sheet.setFrozenColumns(4);sheet.getRange(1,1,1,headers.length).setBackground('#eeeeee').setFontWeight('bold').setWrap(true);}return sheet;}
function safe_(s){return /^[=+\-@\t\r]/.test(s)?"'"+s:s;}
function escaped_(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function normalize_(d){let filled=0,partial=0,blank=0;const quantities=[];PRODUCTS.forEach(p=>{let entered=0;const sizes=p.sizes.length?p.sizes:[''];sizes.forEach(size=>{const v=size?d.values[p.id]?.[size]:d.values[p.id];if(v===undefined||v===null||v===''){quantities.push('');return;}if(typeof v!=='string'||!v.trim()||!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1000000000)throw Error('Invalid quantity '+p.id);quantities.push(Number(v));entered++;});if(entered===sizes.length)filled++;else if(entered)partial++;else blank++;});return {quantities:quantities,filled:filled,partial:partial,blank:blank,filledFields:quantities.filter(v=>v!=='').length};}
function findReceipt_(sheet,id){if(sheet.getLastRow()<2)return null;return sheet.getRange(2,1,sheet.getLastRow()-1,1).createTextFinder(id).matchEntireCell(true).findNext();}
function doPost(e){const lock=LockService.getScriptLock();let row;try{const d=JSON.parse(e.parameter.payload||'');if(!/^[a-f0-9-]{36}$/.test(d.id)||typeof d.branch!=='string'||typeof d.employee!=='string'||!d.branch.trim()||!d.employee.trim()||d.branch.length>100||d.employee.length>100||!d.values||typeof d.values!=='object')throw Error('Invalid details');const counts=normalize_(d);if(!counts.filledFields)throw Error('Enter at least one quantity');lock.waitLock(30000);const sheet=sheet_();const existing=findReceipt_(sheet,d.id);if(existing)row=existing.getRow();else{sheet.appendRow([d.id,Utilities.formatDate(new Date(),'Asia/Riyadh','yyyy-MM-dd HH:mm:ss'),safe_(d.branch.trim()),safe_(d.employee.trim()),counts.filled,counts.partial,counts.blank,counts.filledFields,counts.quantities.length-counts.filledFields,'Pending','',...counts.quantities]);SpreadsheetApp.flush();row=sheet.getLastRow();}}catch(err){console.error(String(err));return ContentService.createTextOutput('Rejected');}finally{if(lock.hasLock())lock.releaseLock();}try{sendReport_(row);}catch(err){console.error(String(err));}return ContentService.createTextOutput('Saved');}
function report_(row){const fields=fields_();const details=fields.map((f,i)=>({code:f.p.code,name:f.p.name,unit:f.p.unit,size:f.size,qty:row[11+i],status:row[11+i]===''?'Not filled':'Filled'}));const missing=details.filter(d=>d.status==='Not filled');const summary='Branch: '+row[2]+'\nEmployee: '+row[3]+'\nSubmitted (Riyadh): '+row[1]+'\nReceipt: '+row[0]+'\nTotal products: '+PRODUCTS.length+'\nFilled products: '+row[4]+'\nPartly filled products: '+row[5]+'\nNot filled products: '+row[6]+'\nFilled quantity fields: '+row[7]+'\nBlank quantity fields: '+row[8]+'\n0 means counted with no stock; blank means not filled.\nGoogle Sheet: https://docs.google.com/spreadsheets/d/'+INVENTORY_SHEET_ID+'/edit';
const body=summary+'\n\nMissing quantities:\n'+(missing.length?missing.map(d=>d.code+' - '+d.name+(d.size?' - '+d.size+' BTL':'') ).join('\n'):'None')+'\n\nFull inventory attached as CSV.';
const csvCell=v=>'"'+safe_(String(v)).replace(/"/g,'""')+'"';
const csv='\uFEFF'+[['Branch',row[2]],['Employee',row[3]],['Submitted at (Riyadh)',row[1]],['Receipt',row[0]],['Code','Product','Unit','Bottle size','Quantity','Status'],...details.map(d=>[d.code,d.name,d.unit,d.size,d.qty,d.status])].map(r=>r.map(csvCell).join(',')).join('\r\n');
const table='<table cellpadding="7" cellspacing="0" style="border-collapse:collapse;width:100%;font-size:12px"><tr style="background:#eeeeee"><th>Code</th><th>Product</th><th>Unit / size</th><th>Quantity</th><th>Status</th></tr>'+details.map(d=>'<tr style="border-bottom:1px solid #ddd"><td>'+escaped_(d.code)+'</td><td>'+escaped_(d.name)+'</td><td>'+escaped_(d.size?d.size+' BTL':d.unit)+'</td><td>'+escaped_(d.qty===''?'—':d.qty)+'</td><td>'+escaped_(d.status)+'</td></tr>').join('')+'</table>';
return {subject:'Blue Sky Inventory | '+String(row[2]).replace(/[\r\n]/g,' ')+' | '+row[1]+' | '+row[4]+'/'+PRODUCTS.length+' products filled',body:body,htmlBody:'<div style="font-family:Arial;color:#0d2340"><h2>Branch inventory report</h2><p style="white-space:pre-line">'+escaped_(summary)+'</p>'+table+'<p>Developer: @Eng. Faizal Emam<br><a href="https://itdelhi.in">itdelhi.in</a></p></div>',csv:csv};}
function sendReport_(rowNumber){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const sheet=sheet_(),row=sheet.getRange(rowNumber,1,1,11+fields_().length).getValues()[0];if(!['Pending','Failed'].includes(row[9]))return;if(MailApp.getRemainingDailyQuota()<2){sheet.getRange(rowNumber,11).setValue('Daily email quota exhausted; queued for retry');return;}const report=report_(row);sheet.getRange(rowNumber,10,1,2).setValues([['Sending','']]);SpreadsheetApp.flush();try{verifyInventorySender();GmailApp.sendEmail(EMAIL_TO,report.subject,report.body,{from:EMAIL_FROM,replyTo:EMAIL_FROM,cc:EMAIL_CC,htmlBody:report.htmlBody,name:'Blue Sky Inventory',attachments:[Utilities.newBlob(report.csv,'text/csv','BlueSky-Inventory-'+row[0]+'.csv')]});sheet.getRange(rowNumber,10,1,2).setValues([['Sent','']]);}catch(err){sheet.getRange(rowNumber,10,1,2).setValues([['Failed',safe_(String(err).slice(0,500))]]);}SpreadsheetApp.flush();}finally{lock.releaseLock();}}
function retryPendingEmails(){const sheet=sheet_();if(sheet.getLastRow()<2)return;const statuses=sheet.getRange(2,10,sheet.getLastRow()-1,1).getValues();let handled=0;for(let i=0;i<statuses.length&&handled<10;i++)if(['Pending','Failed'].includes(statuses[i][0])){sendReport_(i+2);handled++;}}
function setupInventory(){verifyInventorySender();sheet_();MailApp.getRemainingDailyQuota();if(!ScriptApp.getProjectTriggers().some(t=>t.getHandlerFunction()==='retryPendingEmails'))ScriptApp.newTrigger('retryPendingEmails').timeBased().everyMinutes(5).create();console.log('Inventory sheet and email retry trigger ready. Now deploy as a Web app.');}
function doGet(e){const id=String(e.parameter.id||'');let result={saved:false};if(e.parameter.action==='status'&&/^[a-f0-9-]{36}$/.test(id)){const sheet=sheet_(),cell=findReceipt_(sheet,id);if(cell){const values=sheet.getRange(cell.getRow(),5,1,6).getValues()[0];result={saved:true,filled:values[0],partial:values[1],blank:values[2],emailStatus:values[5]};}}const json=JSON.stringify(result);return ContentService.createTextOutput(e.parameter.callback==='bscReceipt'?'bscReceipt('+json+');':json).setMimeType(e.parameter.callback==='bscReceipt'?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON);}
