// Used with Code.gs + Catalog.gs. ReadyToDeploy.gs already includes this file; do not add it twice.

const BRANCH_NAMES=["AIRPORT ROAD","FAISALIYAH","KHODARIYAH","SAFWA SAHIK","SAIHAT","FAKHRIYAH","SAHAB 1","SAHAB 2","SAPTCO","ABUHAIDERIYAH","AQRABIYAH","AZIZIYAH 1","DOHA","ESKAN","HALF MOON","JAMA'A","NAFOURA","JESSER 2","RAKAH","TAHLIYAH ABBASI","TAWUN KHALEEJ","JB KURBI","JB TAABA","HASSA 1","HASSA 5","HASSA 6","QATIF","WATANI HOSPITAL","RIYADH 2","RIYADH 4","RIYADH 5","RIYADH 6","RIYADH 8","RIYADH 9","RIYADH 10","HAFAR 1","HAFER 4","NAIRIYAH"];
const MAX_BY_UNIT={PCS:5000,UNIT:5000,PKT:2000,ROLL:2000,BTL:500,KG:1000,ML:100000,GRM:100000,LTR:1000,SACHET:5000,CAN:5000,CRT:5000,CUP:50000,BOX:5000};
const WHOLE_NUMBER_UNITS=['PCS','UNIT','UNITS','PKT','ROLL','BTL','SACHET','CAN','CRT','CUP','BOX'];
function unitBase_(unit){const base=String(unit).toUpperCase().split('*')[0].trim();return base==='UNITS'?'UNIT':base;}
function pinHash_(salt,pin){return adminDigest_(salt+':'+pin);}
function randomPin_(){const b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,Utilities.getUuid()+Utilities.getUuid());const n=((b[0]&255)<<16)|((b[1]&255)<<8)|(b[2]&255);return String(100000+n%900000);}
function setupBranchPins(){adminEditor_();const lock=LockService.getScriptLock();lock.waitLock(30000);try{const props=PropertiesService.getScriptProperties();BRANCH_NAMES.forEach(name=>{const key='BSC_PIN_'+adminDigest_(name);if(props.getProperty(key)){console.log('SKIPPED (already has PIN): '+name);return;}const pin=randomPin_(),salt=Utilities.getUuid();props.setProperty(key,JSON.stringify({salt:salt,hash:pinHash_(salt,pin)}));console.log('BRANCH: '+name+' | PIN: '+pin);});}finally{lock.releaseLock();}}
function resetBranchPin(){adminEditor_();const name='PASTE BRANCH NAME HERE';if(!BRANCH_NAMES.includes(name))throw Error('Unknown branch name.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const pin=randomPin_(),salt=Utilities.getUuid(),props=PropertiesService.getScriptProperties();props.setProperty('BSC_PIN_'+adminDigest_(name),JSON.stringify({salt:salt,hash:pinHash_(salt,pin)}));props.deleteProperty('BSC_PINRATE_'+adminDigest_(name));console.log('BRANCH: '+name+' | NEW PIN: '+pin);}finally{lock.releaseLock();}}
function checkBranchPin_(branch,pin){const props=PropertiesService.getScriptProperties(),k=adminDigest_(branch),now=Date.now(),acct=JSON.parse(props.getProperty('BSC_PIN_'+k)||'null');if(!acct)throw Error('Branch PIN is not configured. Contact the inventory administrator.');let rate=JSON.parse(props.getProperty('BSC_PINRATE_'+k)||'null');if(!rate||now>rate.until)rate={count:0,until:now+15*60*1000};if(rate.count>=5)throw Error('Branch PIN locked. Try again after 15 minutes.');if(typeof pin!=='string'||!/^\d{6}$/.test(pin)||pinHash_(acct.salt,pin)!==acct.hash){rate.count++;props.setProperty('BSC_PINRATE_'+k,JSON.stringify(rate));throw Error(rate.count>=5?'Branch PIN locked. Try again after 15 minutes.':'Incorrect branch PIN. Please check your PIN and retry.');}props.deleteProperty('BSC_PINRATE_'+k);}
function checkLimits_(d){PRODUCTS.forEach(p=>(p.sizes.length?p.sizes:['']).forEach(size=>{const v=size?d.values[p.id]?.[size]:d.values[p.id];if(v===undefined||v===null||v==='')return;const n=Number(v),unit=unitBase_(p.unit),max=MAX_BY_UNIT[unit]||5000;if(!Number.isFinite(n)||n<0)throw Error('Invalid quantity: '+p.code);if(n>max)throw Error('Quantity limit exceeded: '+p.code+' (maximum '+max+'). Contact the administrator if this stock is correct.');if(WHOLE_NUMBER_UNITS.includes(unit)&&!Number.isInteger(n))throw Error('Whole-number quantity required: '+p.code+'.');}));}
function revisionColumns_(sheet){const col=12+fields_().length;if(sheet.getMaxColumns()<col+1)sheet.insertColumnsAfter(sheet.getMaxColumns(),col+1-sheet.getMaxColumns());sheet.getRange(1,col,1,2).setValues([['Report status','Superseded by']]);return col;}
function dayOf_(v){return v instanceof Date?Utilities.formatDate(v,'Asia/Riyadh','yyyy-MM-dd'):String(v).slice(0,10);}
function recordRevision_(sheet,row,branch,day,id){const col=revisionColumns_(sheet),last=sheet.getLastRow();sheet.getRange(row,col,1,2).setValues([['Current','']]);if(last<3)return;const metadata=sheet.getRange(2,1,last-1,3).getValues();metadata.forEach((r,i)=>{if(i+2!==row&&String(r[2])===branch&&dayOf_(r[1])===day)sheet.getRange(i+2,col,1,2).setValues([['Superseded',id]]);});}
function cacheSubmissionError_(d,message){if(d&&typeof d.id==='string'&&/^[a-f0-9-]{36}$/.test(d.id)&&typeof d.attempt==='string'&&/^[a-f0-9-]{36}$/.test(d.attempt))CacheService.getScriptCache().put('BSC_ERROR_'+d.id+'_'+d.attempt,JSON.stringify({saved:false,error:message}),300);}
function submissionError_(id,attempt){if(!/^[a-f0-9-]{36}$/.test(id)||!/^[a-f0-9-]{36}$/.test(attempt))return null;const cached=CacheService.getScriptCache().get('BSC_ERROR_'+id+'_'+attempt);return cached?JSON.parse(cached):null;}
function doPost(e){const lock=LockService.getScriptLock();let row,d;try{d=JSON.parse(e.parameter.payload||'');if(!/^[a-f0-9-]{36}$/.test(d.id)||typeof d.branch!=='string'||typeof d.employee!=='string'||!d.branch.trim()||!d.employee.trim()||d.branch.length>100||d.employee.length>100||!d.values||typeof d.values!=='object')throw Error('Invalid branch or employee details.');if(d.website)throw Error('Submission rejected. Please reload the form.');const branch=d.branch.trim();if(!BRANCH_NAMES.includes(branch))throw Error('Select a valid branch from the list.');lock.waitLock(30000);checkBranchPin_(branch,d.pin);const sheet=sheet_(),existing=findReceipt_(sheet,d.id);if(existing){row=existing.getRow();if(String(sheet.getRange(row,3).getValue())!==branch)throw Error('Reference belongs to another branch.');}else{checkLimits_(d);const counts=normalize_(d);if(counts.filled!==PRODUCTS.length)throw Error('All product quantities are mandatory. Enter 0 for no stock.');const at=Utilities.formatDate(new Date(),'Asia/Riyadh','yyyy-MM-dd HH:mm:ss');sheet.appendRow([d.id,at,safe_(branch),safe_(d.employee.trim()),counts.filled,counts.partial,counts.blank,counts.filledFields,counts.quantities.length-counts.filledFields,'Pending','',...counts.quantities]);row=sheet.getLastRow();recordRevision_(sheet,row,branch,at.slice(0,10),d.id);SpreadsheetApp.flush();}}catch(err){const message=String(err.message||'Submission failed. Please retry.');cacheSubmissionError_(d,message);console.error(message);return ContentService.createTextOutput('Rejected');}finally{if(lock.hasLock())lock.releaseLock();}try{sendReport_(row);}catch(err){console.error(String(err));}return ContentService.createTextOutput('Saved');}
